### ISSUE TITLE
Error C2039 after updating VS 2019 from 16.3.9 to 16.11.11

### ISSUE THREAD

**Issue by prospectumdev** [fnc12/sqlite_orm#997]
I upgraded VS from 16.3.9 to 16.11.11.

Now, at least in some projects, I get C2039 errors like

1>D:\share\3rdparty\sqlite_orm\include\sqlite_orm\sqlite_orm.h(16419,68): error C2039: "bind" ist kein Member von 1>"sqlite_orm::statement_binder<T,void>".
1>        with
1>        [
1>            T=int vpolab::model::workspace::_seg_08_ConvolutionNoteSettings::*
1>        ]

Other projects compile as expected.

Now the question is:

- Did I use sqlite_orm in a way that is not compatible with the new compiler? If this problem is known/common and a standard solution exists, I might be able to fix my project without spending a lot of time investigating what is going on.
- Is it maybe a compatibility issue within sqlite_orm?

Thank you very much!

**Comment by fnc12** [comment]
please provide a code snippet to repro the error

**Comment by prospectumdev** [comment]
It is most likely this line

`auto convNoteSettings = workspaceDB->get<_seg_08_ConvolutionNoteSettings>(where(c(&_seg_08_ConvolutionNoteSettings::convolutionGroup_id) == convolutionGroupID and c(&_seg_08_ConvolutionNoteSettings::MIDINoteNumber) == attackDescription.NormalMIDINoteNumber));`

**Comment by prospectumdev** [comment]
Sorry for having bothered you - I have found and fixed the problem. It was in my code. Not an sqlite_orm problem but rather the consequence of a long working day... Now everything works nicely again.
