### PR TITLE
Detect the absence of string_view's iterator range ctor differently.

### LINKED ISSUE #1149: Fails to compile with Xcode 14.2
Using:
* sqlite_orm 1.8.1 (via vcpkg 2023.02.24)
* cmake with `CMAKE_CXX_STANDARD` set to 20
* GitHub Actions `macos-latest` (a.k.a. `macos-12`) image

Getting the following error:
```
In file included from /Users/runner/work/<snip>:
/Users/runner/work/<snip>/_build/vcpkg_installed/x64-osx/include/sqlite_orm/sqlite_orm.h:12687:23: error: no matching constructor for initialization of 'std::string_view' (aka 'basic_string_view<char>')
                os << std::string_view{it, next};
                      ^               ~~~~~~~~~~
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/string_view:267:5: note: candidate constructor not viable: no known conversion from 'std::string::const_iterator' (aka '__wrap_iter<const char *>') to 'const char *' for 1st argument
    basic_string_view(const _CharT* __s, size_type __len) _NOEXCEPT
    ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/string_view:261:5: note: candidate constructor not viable: requires 1 argument, but 2 were provided
    basic_string_view(const basic_string_view&) _NOEXCEPT = default;
    ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/string_view:276:5: note: candidate constructor not viable: requires single argument '__s', but 2 arguments were provided
    basic_string_view(const _CharT* __s)
    ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/string_view:258:5: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
    basic_string_view() _NOEXCEPT : __data (nullptr), __size(0) {}
    ^
1 error generated.
```

Same code with `CMAKE_CXX_STANDARD` set to 17 builds fine.

### PR DESCRIPTION
**Pull request by trueqbit**
Fixes #1149.

There are environments that don't support the iterator constructor of string_view yet. E.g. XCode 14.2 on macos ships with libc++ 14, yet XCode picks up libc++ 13 installed on the system.

This PR uses concepts to pick the right version of `stream_sql_escaped()`.

### CODE REVIEW

**Review by fnc12 — APPROVED** [review]

File: dev/serializing_util.h [hunk 1]
```diff
@@ -29,9 +29,14 @@ namespace sqlite_orm {
...
         std::string serialize_order_by(const T& t, const Ctx& context);
 
-#if __cplusplus >= 202002L &&                                                                                          \
-    __cpp_lib_concepts  //  contiguous iterator ranges depend on contiguous_iterator, sized_sentinel_for in all major implementations
-        inline void stream_sql_escaped(std::ostream& os, const std::string& str, char char2Escape) {
+#ifdef SQLITE_ORM_CONCEPTS_SUPPORTED
+        // optimized version when string_view's iterator range constructor is available
+        template<class SFINAE = void>
+        void stream_sql_escaped(std::ostream& os, const std::string& str, char char2Escape)
+            requires requires {
```
[the remark this answers is not in the document]
Comment (trueqbit) [reply dev/serializing_util.h:36]: Yeah, quite _\<fill in your favourite thought>_ 🥢
The first is a requires-clause, the other an unnamed requires-expression (i.e. the concept itself in this case).

For a bit of clarity, see the [notes](https://en.cppreference.com/w/cpp/language/requires) on the bottom of the C++ documentation.

**Review by fnc12 — APPROVED** [review]
