### ISSUE TITLE
wide string test case (in tests3.cpp) does not compile correctly when using storage.dump()

### ISSUE THREAD

**Issue by juandent** [fnc12/sqlite_orm#624]
I added to TEST_CASE("Wide string") the following:

```
   auto all = storage.get_all<Alphabet>();
    std::cout << "all = " << all.size() << std::endl;
    for (auto& alpha : all) {
        std::cout << storage.dump(alpha) << std::endl;
    }
```

and added an `#include <iostream>` and when I compile with Visual C++ 2019 (Version 16.7.7) I get:

sqlite_orm\include\sqlite_orm/sqlite_orm.h(1543,1): error C2679: binary '<<': no operator found which takes a right-hand operand of type 'const T' (or there is no acceptable conversion)
1>        with
1>        [
1>            T=field_type
1>        ]

the line the error points to includes this code:

```
    template<class T>
    struct field_printer {
        std::string operator()(const T &t) const {
            std::stringstream stream;
            stream << t;                                          // THIS CAUSES THE ERROR, T is wstring
            return stream.str();
        }
    };
```

To correct it I defined thhis code (which is incomplete):

```
namespace sqlite_orm {

    /**
     *  Is used to print members mapped to objects in storage_t::dump member function.
     *  Other developers can create own specialization to map custom types
     */
    template<>
    struct field_printer<std::wstring> {
        std::string operator()(const std::wstring& t) const {
            std::wstringstream stream;
            stream << t;
            return " "; // stream.str();                                // NEEED TO TRANSFORM wstring to string!
        }
    };
}
```

So I almost have the solution: find how to transform a wstring to a string!!

Please help

Juan

**Comment by fnc12** [comment]
there is no the one and only correct way to convert wide string to string cause wide string contains two bytes per char and string contains only one. One of them exist in sqlite_orm in `row_extractor` class in `std::wstring` specialization. One thing: it is covered with `#ifndef SQLITE_ORM_OMITS_CODECVT` macro cause it uses `#include <codecvt>` which became deprecated in the latest c++ standards. So all you can do is to add `field_printer`'s specialization for `std::wstring` and make a conversion inside it with the same code just like `row_extractor` has or any other. Hope it helps

**Comment by fnc12** [comment]
@juandent is the issue actual?

**Comment by juandent** [comment]
the issue is still on the table -- dump will not compile if the mapped struct has a wstring member

**Comment by juandent** [comment]
My suggestion for a solution is to add a field_printer for wide strings with a default (although not perfect ) conversion to narrow strings taken from row_extractor, like so:

```c++
namespace sqlite_orm {

    /**
     *  Is used to print members mapped to objects in storage_t::dump member function.
     *  Other developers can create own specialization to map custom types
     */
    template<>
    struct field_printer<std::wstring> {
        std::string operator()(const std::wstring& t) const {
            std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>> converter;
            return converter.to_bytes(t);
        }
    };
}
```

Then you can add this to test it works:

```c++
    auto rows = storage.get_all<Alphabet>();
    for( auto& r : rows) {
        storage.dump(r);
    }
```

Would be nice to have that come with sqlite_orm right?

I suggest adding it @fnc12

**Comment by juandent** [comment]
One but: I cannot see the output in the test controller so i cannot verify how the wstrings are converted to strings! -- maybe don't know how to use the unit test dialog!!

**Comment by fnc12** [comment]
@juandent this is a nice solution but I will not add it cause:
1) `wstring_convert` is deprecated in C++20
2) the way you convert strings is user related. It means someone may want to do it another way and not with utf8

**Comment by juandent** [comment]
Understood!! I guess its time to close this then
