### ISSUE TITLE
The build with clang 19.1.0 fails in c++20 mode.

### ISSUE THREAD

**Issue by lemourin** [fnc12/sqlite_orm#1358]
Compiler log:

```cpp
.../include/sqlite_orm/sqlite_orm.h:1321:20: error: cannot initialize return object of type 'size_t' (aka 'unsigned long') with an lvalue of type '<dependent type>'
 1321 |             return Idx...[Pos];
```

Interestingly enough, `clang` still defines `__cpp_pack_indexing` to `202311L` even though I compile with `-std=c++20` which is probably incorrect on the compiler side.

**Comment by theo-dep** [comment]
I have a same issue using clang-tidy 19.1.1 on Ubuntu and -std=c++23

**Comment by fedorchikthebest** [comment]
it trows this error
`  The link interface of target "sqlite_orm::sqlite_orm" contains:

    SQLite::SQLite3

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /usr/local/lib/cmake/SqliteOrm/SqliteOrmConfig.cmake:4 (include)
  CMakeLists.txt:33 (find_package)
`

**Comment by Arteiimis** [comment]
any plan to fix this?

**Comment by fnc12** [comment]
@Arteiimis yeah. I put it on the public board. Will be fixed soon

**Comment by trueqbit** [comment]
Who would have known that clang enables pack indexing [in all language modes](https://github.com/llvm/llvm-project/pull/101956) just like that...
Yet clang's real problem is that its expression evaluation is wrong. Thx @theo-dep for pointing out that a return type of `auto` works.
The second weirdness is the compiler warning, which doesn't make any sense. Either unconditionally supported or not.

@Arteiimis It would be nice if you would improve your problem report to the llvm project and report two different things with a clear example [similar to this one](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXAAx8BBAKoBnTAAUAHp0m8AVhNK0mDUMgCkAJgBCZ86SX1kBPAMqN0AYVS0AriwYSArKQuADJ4DJgAct4ARpjEIABspAAOqAqEjgzuXj7%2ByanpAiFhkSwxcYm2mPYZQgRMxARZ3r5cAZXVArX1BEUR0bEJNnUNTTmtQ929JWUJAJQ2qJ7EyOwcZgDMocheWADUxuuung60hACeB9jGkgCCG1s7mPuHjgoExJisl9d3t/dUuwA%2BoDkEkkoCkkxkABrQGhLCqULAZ5XdYAEV2pkkpnWXC4QR%2BBEwLCS%2BiJB1cb3QIBAaQAXphAQRdspUqRdlSafTGQQAHT83YASXQqm%2BtzQDDemFUSWIuyYx1Qu3h0sBSgAjp5GCtAQA3MRawFMAgQTkgFWqNWYTXazAU4Wqfm8y6zfYAdkst123t2HwISwYQpFTuMfnMrIUobRB09dzd0b%2BOJceCoPx%2BoWZLCYoQgruMHrTOJTQJBYIhUNhFqRKIOGKxOLxBK9PolUplcoVRF2qmeGItVptDB1%2Bq8jONFNMnkupoI1PNDARA61Q7th2kuy47NM3wL8dmMZ%2BPo5s5paGOz1cFO7B8T62Tqb%2B8Y481onD8vF8HE0pFQnEvFisDlFmWJ4Nh4UgCA0Z95mhEBTAAFl5ABOPwuAADlQ%2BD4ngrg3UkLgkPWPROHgj8oJ/TheAUEBpEgr9n1IOBYCQaUqkVMgKAgepgAUZQDEwWghAQVAAHdP3AtASToY0Mj4sJBOEsTyMkpI6AGbYDGAAipFIFS1OIcJWFWXg9PoYgAHljiE0TP2/VjkBuYgeMowJVCqWp8E/Xh%2BEEEQxHYHSfPkJQ1HInQiP0QwUCsKw9DwKJqMgeZUCSBwBGojgAFoqVrEwAIsLhSJ/XVYmIPAsES3Nkn4wy2E4bA3OQdjuzQ%2BJMuw3YNMMDckN5LheUkXZ/0sCwsV4YhPEEPA2AAFVQDxKvmBRgJWXQqVCOSBOspTuF4ETiCYJJOB4F83zI%2BiKI4Bq2KIOVVFa9r4M6yLkQIvqBqGmLRu/OjNFmeYEE%2BLA4iq2CcWQt03XWeJJHgpC0KQ%2BD4NMRJXw4IqWAkSRpFs3hfw4KiaIgqD5iYxAQHs9jyEobjeP4hSbOOkzUCkslZPp7bcd0lnVLMlAXu06RTNiWrjO51nYks4RFK5%2BzHOcgnXPc2dQhcoK/PEQLZEUFR1AunRTD0TTovy6xTgS%2BBktSjIMuy2dcq%2B8wcTxkriDKirLeq4ojPqxrmvutqOq617ev6wbhqsZ3SAmqbZvm2hFoWJZVs3daGE2hmdvA95MHYaR9sOpnTo4d9SC5/Hrqa26WsDp7g5697w8dqPfug0hAaYYHKBguC/F5VrUII9Z1j8N0/HgyQ0Pg4j0fO798cJ2iScYmBycp27qa4py6fkzmmfF3mZIEDO94u4W4mDwWD/00WXPPqXT7sxr5Yy3h7I81XFfV0RNekIKddCvrXQL0TYjTNvFROKU0qSk4HbdADtTamGQC7Uq5VMCJ0hN7OqV0/bVwDo9Z6mkG5h0%2Bog%2BI41JoODjgtT2y1k4BSGJ5E%2BMt94FyOrtYupdy6%2BxuiQGuBD65vRIRHUa5Dib0X%2BqQMGfcsR%2BHiPENCeE8S4nguPGeRVuGK2okvCRxdTBzzxi5VukjXZpCcPBIAA%3D%3D).

**Comment by Arteiimis** [comment]
> Who would have known that clang enables pack indexing [in all language modes](https://github.com/llvm/llvm-project/pull/101956) just like that... Yet clang's real problem is that its expression evaluation is wrong. Thx [@theo-dep](https://github.com/theo-dep) for pointing out that a return type of `auto` works. The second weirdness is the compiler warning, which doesn't make any sense. Either unconditionally supported or not.
> 
> [@Arteiimis](https://github.com/Arteiimis) It would be nice if you would improve your problem report to the llvm project and report two different things with a clear example [similar to this one](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXAAx8BBAKoBnTAAUAHp0m8AVhNK0mDUMgCkAJgBCZ86SX1kBPAMqN0AYVS0AriwYSArKQuADJ4DJgAct4ARpjEIABspAAOqAqEjgzuXj7%2ByanpAiFhkSwxcYm2mPYZQgRMxARZ3r5cAZXVArX1BEUR0bEJNnUNTTmtQ929JWUJAJQ2qJ7EyOwcZgDMocheWADUxuuung60hACeB9jGkgCCG1s7mPuHjgoExJisl9d3t/dUuwA%2BoDkEkkoCkkxkABrQGhLCqULAZ5XdYAEV2pkkpnWXC4QR%2BBEwLCS%2BiJB1cb3QIBAaQAXphAQRdspUqRdlSafTGQQAHT83YASXQqm%2BtzQDDemFUSWIuyYx1Qu3h0sBSgAjp5GCtAQA3MRawFMAgQTkgFWqNWYTXazAU4Wqfm8y6zfYAdkst123t2HwISwYQpFTuMfnMrIUobRB09dzd0b%2BOJceCoPx%2BoWZLCYoQgruMHrTOJTQJBYIhUNhFqRKIOGKxOLxBK9PolUplcoVRF2qmeGItVptDB1%2Bq8jONFNMnkupoI1PNDARA61Q7th2kuy47NM3wL8dmMZ%2BPo5s5paGOz1cFO7B8T62Tqb%2B8Y481onD8vF8HE0pFQnEvFisDlFmWJ4Nh4UgCA0Z95mhEBTAAFl5ABOPwuAADlQ%2BD4ngrg3UkLgkPWPROHgj8oJ/TheAUEBpEgr9n1IOBYCQaUqkVMgKAgepgAUZQDEwWghAQVAAHdP3AtASToY0Mj4sJBOEsTyMkpI6AGbYDGAAipFIFS1OIcJWFWXg9PoYgAHljiE0TP2/VjkBuYgeMowJVCqWp8E/Xh%2BEEEQxHYHSfPkJQ1HInQiP0QwUCsKw9DwKJqMgeZUCSBwBGojgAFoqVrEwAIsLhSJ/XVYmIPAsES3Nkn4wy2E4bA3OQdjuzQ%2BJMuw3YNMMDckN5LheUkXZ/0sCwsV4YhPEEPA2AAFVQDxKvmBRgJWXQqVCOSBOspTuF4ETiCYJJOB4F83zI%2BiKI4Bq2KIOVVFa9r4M6yLkQIvqBqGmLRu/OjNFmeYEE%2BLA4iq2CcWQt03XWeJJHgpC0KQ%2BD4NMRJXw4IqWAkSRpFs3hfw4KiaIgqD5iYxAQHs9jyEobjeP4hSbOOkzUCkslZPp7bcd0lnVLMlAXu06RTNiWrjO51nYks4RFK5%2BzHOcgnXPc2dQhcoK/PEQLZEUFR1AunRTD0TTovy6xTgS%2BBktSjIMuy2dcq%2B8wcTxkriDKirLeq4ojPqxrmvutqOq617ev6wbhqsZ3SAmqbZvm2hFoWJZVs3daGE2hmdvA95MHYaR9sOpnTo4d9SC5/Hrqa26WsDp7g5697w8dqPfug0hAaYYHKBguC/F5VrUII9Z1j8N0/HgyQ0Pg4j0fO798cJ2iScYmBycp27qa4py6fkzmmfF3mZIEDO94u4W4mDwWD/00WXPPqXT7sxr5Yy3h7I81XFfV0RNekIKddCvrXQL0TYjTNvFROKU0qSk4HbdADtTamGQC7Uq5VMCJ0hN7OqV0/bVwDo9Z6mkG5h0%2Bog%2BI41JoODjgtT2y1k4BSGJ5E%2BMt94FyOrtYupdy6%2BxuiQGuBD65vRIRHUa5Dib0X%2BqQMGfcsR%2BHiPENCeE8S4nguPGeRVuGK2okvCRxdTBzzxi5VukjXZpCcPBIAA%3D%3D).

https://github.com/llvm/llvm-project/issues/123074#issuecomment-2607757031

maybe a clang bug, godbolt links in the comment above.

**Comment by Arteiimis** [comment]
https://github.com/llvm/llvm-project/pull/121405
